on:
  push:
    branches:
      - 1.16

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Chmod gradlew
      run: chmod a+x ./gradlew
    - name : Run Gradle
      run: ./gradlew clean build publishToMavenLocal
    - uses: actions/cache@v2
      with:
        path: |
         ~/.gradle/caches
         ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        - uses: meeDamian/github-release@2.0
          with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.MY_CUSTOM_TAG }}
          name: My Creative Name
            body: >
            This release actually changes the fabric of the reality, so be careful 
            while applying, as error in database migration, can irrecoverably wipe 
            some laws of physics.  
          gzip: folders
    files: >
      Dockerfile
      action.yml
     .github/
      license:LICENSE
      work-flows:.github/
      with: 
        name: LibVulpes-1.16.3 
        path: ${{ github.workspace }}/output/**
