on:
  push:
    branches:
      - 1.16

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Chmod gradlew
      run: chmod a+x ./gradlew
    - name: Build with Gradle
      run: ./gradlew clean build publishToMavenLocal

name: my-artifact
    steps:
    - run:
        mkdir -p ${{ github.workspace }}/artifact
        echo hello > ${{ github.workspace }}/artifact/world.txt
    - uses: actions/upload-artifact@v2
      with: 
        name: ${{ env.name }}-name  
        path: ${{ github.workspace }}/artifact/**/*


